project_id = "hzcrkipdqaqklrnikcrm"

[functions.extract-treatments]
verify_jwt = false

[functions.representation-history]
verify_jwt = false

[functions.extract-demand]
verify_jwt = false

[functions.extract-specials]
verify_jwt = false

[functions.extract-treatment-timeline]
verify_jwt = false

[functions.extract-injuries]
verify_jwt = false