/**
 * ReviewerIQ — Medical Review Issue Types
 *
 * Explainable, evidence-linked review issues generated by the rule engine.
 * Each issue carries enough context for a reviewer to make a disposition.
 */

// ─── Issue Types ────────────────────────────────────────

export type ReviewIssueType =
  | "excessive_visit_frequency"
  | "treatment_beyond_recovery_window"
  | "repeated_passive_modalities"
  | "duplicate_service"
  | "escalation_without_findings"
  | "code_note_mismatch"
  | "bill_no_treatment_note"
  | "treatment_no_bill"
  | "prolonged_care_weak_findings"
  | "high_variance_pricing"
  | "missing_documentation"
  | "duplicate_bill_line"
  | "provider_concern"
  | "near_identical_notes"
  | "gap_then_intensive_care"
  | "provider_utilization_pattern";

// ─── Clinical Issue Categories ──────────────────────────

export type ClinicalIssueCategory =
  | "duration"
  | "frequency"
  | "passive_care"
  | "escalation"
  | "documentation"
  | "note_pattern"
  | "financial";

export const ISSUE_CATEGORY_MAP: Record<ReviewIssueType, ClinicalIssueCategory> = {
  excessive_visit_frequency: "frequency",
  treatment_beyond_recovery_window: "duration",
  repeated_passive_modalities: "passive_care",
  duplicate_service: "frequency",
  escalation_without_findings: "escalation",
  code_note_mismatch: "documentation",
  bill_no_treatment_note: "documentation",
  treatment_no_bill: "documentation",
  prolonged_care_weak_findings: "duration",
  high_variance_pricing: "financial",
  missing_documentation: "documentation",
  duplicate_bill_line: "financial",
  provider_concern: "frequency",
  near_identical_notes: "note_pattern",
  gap_then_intensive_care: "frequency",
  provider_utilization_pattern: "frequency",
};

export const CLINICAL_CATEGORY_LABEL: Record<ClinicalIssueCategory, string> = {
  duration: "Duration Concern",
  frequency: "Frequency Concern",
  passive_care: "Passive Care Concern",
  escalation: "Escalation Concern",
  documentation: "Documentation Support Concern",
  note_pattern: "Note-Pattern Concern",
  financial: "Financial Concern",
};

export type ReviewIssueSeverity = "critical" | "high" | "medium" | "low" | "info";

export type ReviewIssueDisposition =
  | "pending"
  | "accepted"
  | "reduced"
  | "denied"
  | "uncertain"
  | "escalated"
  | "dismissed";

export interface ReviewIssue {
  id: string;
  tenant_id: string;
  case_id: string;
  /** Issue classification */
  issue_type: ReviewIssueType;
  severity: ReviewIssueSeverity;
  title: string;
  description: string;
  /** Machine-generated explanation */
  machine_explanation: string;
  /** Affected entities */
  affected_provider: string | null;
  affected_date_start: string | null;
  affected_date_end: string | null;
  affected_bill_line_ids: string[];
  affected_treatment_ids: string[];
  /** Evidence linkage */
  evidence: ReviewIssueEvidence[];
  /** Financial impact */
  questioned_amount: number;
  /** Reviewer disposition */
  disposition: ReviewIssueDisposition;
  disposition_rationale: string;
  disposition_by: string | null;
  disposition_at: string | null;
  /** Disposition history for audit */
  disposition_history: DispositionHistoryEntry[];
  created_at: string;
  updated_at: string;
}

export interface ReviewIssueEvidence {
  source_document_id: string | null;
  source_page: number | null;
  quoted_text: string;
  relevance: string;
}

export interface DispositionHistoryEntry {
  disposition: ReviewIssueDisposition;
  rationale: string;
  by: string;
  at: string;
}

// ─── Labels ─────────────────────────────────────────────

export const ISSUE_TYPE_LABEL: Record<ReviewIssueType, string> = {
  excessive_visit_frequency: "Excessive Visit Frequency",
  treatment_beyond_recovery_window: "Treatment Beyond Recovery Window",
  repeated_passive_modalities: "Repeated Passive Modalities",
  duplicate_service: "Duplicate Service",
  escalation_without_findings: "Escalation Without Findings",
  code_note_mismatch: "Code-to-Note Mismatch",
  bill_no_treatment_note: "Bill Without Treatment Note",
  treatment_no_bill: "Treatment Without Bill",
  prolonged_care_weak_findings: "Prolonged Care with Weak Findings",
  high_variance_pricing: "High Variance Pricing",
  missing_documentation: "Missing Documentation",
  duplicate_bill_line: "Duplicate Bill Line",
  provider_concern: "Provider Concern",
};

export const ISSUE_SEVERITY_LABEL: Record<ReviewIssueSeverity, string> = {
  critical: "Critical",
  high: "High",
  medium: "Medium",
  low: "Low",
  info: "Info",
};

export const DISPOSITION_LABEL: Record<ReviewIssueDisposition, string> = {
  pending: "Pending Review",
  accepted: "Accepted as Billed",
  reduced: "Reduced",
  denied: "Denied / Disputed",
  uncertain: "Uncertain",
  escalated: "Escalated",
  dismissed: "Dismissed",
};
